### ISSUE TITLE
A problem with this lib is causing the `az aks list` command to fail

### ISSUE THREAD

**Issue by luisdavim** [Azure/msrest-for-python#122]
You can see more details in this slack thread: 
https://kubernetes.slack.com/archives/C5HJXTT9Q/p1535546773000100

> I think it’s related to api geo-location and trafficmanager failure. I guess the api server returns a paginated list with a http://acs-eastus.trafficmanager.net address as the next page base url. Even if your list is fitting on a single page, that url is tried.
> 
> 3 strange things are going on here, 1. The base url is changed from https://management.azure.com to  http://acs-eastus.trafficmanager.net
> 2. The protocol is now http
> 3. This should be the last page. So why a next_link?

**Comment by luisdavim** [comment]
> I applied a workaround with this patch:

```
+++ /usr/local/Cellar/azure-cli/2.0.45/libexec/lib/python3.7/site-packages/msrest/paging.py	2018-08-29 17:00:37.000000000 +0100
@@ -91,6 +91,8 @@
         :param str url: URL to arbitrary page results.
         """
         self.reset()
+        self.next_link = url.replace('http://acs-eastus.trafficmanager.net','https://management.azure.com')
         return self.advance_page()

     def reset(self):
```

**Comment by lmazuel** [comment]
Hi @luisdavim 
Looks to me like a Traffic Manager issue. I would like to tag the team, but I can't from here. Could you re-open the same issue here:
https://github.com/Azure/azure-sdk-for-python/issues

Anyway, no fix would be done in "msrest" since msrest just follow what the RestAPI told him to do. Thanks!

**Comment by luisdavim** [comment]
https://github.com/Azure/azure-sdk-for-python/issues/3353
