### ISSUE TITLE
Minor typos in python source documentation

### ISSUE THREAD

**Issue by rsimac** [Azure/msrest-for-python#123]
https://github.com/Azure/msrest-for-python/blob/ddbac956c87e67a950759544d8ceedcfec850fbb/msrest/polling/poller.py#L192

The line above says: `:param int timeout: Perion of time to wait for the long running...`

It should say: `:param int timeout: Period, in seconds, of time to wait for the long running...`

minor issue, but somewhat visible because it pops up in IDE when one is looking into how to use methods.

**Comment by lmazuel** [comment]
Thanks for the report @rsimac !
