### ISSUE TITLE
PyPI releases show "Invalid Date"

### ISSUE THREAD

**Issue by adamtheturtle** [Azure/msrest-for-python#131]
See https://pypi.org/project/msrest/#history.

<img width="789" alt="screenshot 2018-11-21 at 00 46 46" src="https://user-images.githubusercontent.com/797801/48811725-efa66600-ed26-11e8-9227-e801b2dc71c3.png">

**Comment by lmazuel** [comment]
I guess it was a temporary warehouse issue, right now it works:
![image](https://user-images.githubusercontent.com/1050156/49116785-873e1400-f253-11e8-943f-a1903370e5e9.png)
