### ISSUE TITLE
I am getting the same kind of error while accessing storage account of kind FileStorage:

### ISSUE THREAD

**Issue by NabeelZaidi** [Azure/msrest-for-python#180]
I am getting the same kind of error while accessing storage account of kind FileStorage:
msrest.exceptions.SerializationError: u'FileStorage' is not valid value for enum <enum 'Kind'
@lmazuel

_Originally posted by @Anshapar in https://github.com/Azure/msrest-for-python/issues/75#issuecomment-496892470_

**Comment by lmazuel** [comment]
Was fixed in msrest 0.4.23, Ansible needs to update their dependency system
