### ISSUE TITLE
stream_upload is not working

### ISSUE THREAD

**Issue by lmcarreiro** [Azure/msrest-for-python#183]
The method `batch_read_file_in_stream` from the Read API of the Computer Vision SDK is not working because of [this stream_upload call](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py#L1716)

I opened this issue https://github.com/Azure/azure-sdk-for-python/issues/8299 there, but now I think that the problem must be fixed here in the msrest lib.

**Comment by lmazuel** [comment]
Closing in favor of the Azure SDK for Python bug
