### ISSUE TITLE
Error when serializing flattened properties with null value as the container object

### ISSUE THREAD

**Issue by RodgeFu** [Azure/msrest-for-python#197]
i found the msrest will report error when serializing flattened properties with null value as the container object, could you help to check? I tried to look at the msrest code, and seems the situation when 'data' is null is not handled in the last screenshot below. thanks.
![image](https://user-images.githubusercontent.com/6038235/78621314-e6cf1980-78b4-11ea-9316-58bee4dbbb38.png)
![image](https://user-images.githubusercontent.com/6038235/78621324-ef275480-78b4-11ea-94b3-29b6350b7218.png)
![image](https://user-images.githubusercontent.com/6038235/78621335-f64e6280-78b4-11ea-972b-b062f01efeab.png)

**Comment by lmazuel** [comment]
Fixed by https://github.com/Azure/msrest-for-python/pull/198
