### ISSUE TITLE
switch ci from travis to GitHub actions

### ISSUE THREAD

**Issue by kapilt** [Azure/msrest-for-python#230]
also ci has been broken on trunk for a few months https://github.com/Azure/msrest-for-python/commits/master

travis has announced they won't support ci builds for opensource projects without payment.

**Comment by lmazuel** [comment]
Hi @kapilt 

It happens I fixed the CI before I saw your issue :). Holiday season is a nice one to catch up this sort of things.

Thanks for the heads-up for Travis. All our packages will migrate to Azure DevOps, and not Github actions eventually, so closing this issue.

Thanks!
