### ISSUE TITLE
0.7.0 incompatible with python 3.5?

### ISSUE THREAD

**Issue by fbrosseau** [Azure/msrest-for-python#251]
Hello,

As documented in release notes, 0.7.0 now requires azure-core. However, unless I am mistaken, that one requires python >= 3.6, which conflicts with msrest's constraints, because msrest claims to support older ones. So now, msrest fails to install on 3.5.

Would it be possible to re-release with a >= 3.6 constraint?

**Comment by simon-castano** [comment]
0.7.0 also breaks python 2.7 compatibility

**Comment by lmazuel** [comment]
@fbrosseau @simon-castano I will release a 0.7.1 Monday with `python_requires` to indicate the end of support of versions pre-3.6 more explicitly (and yank 0.7.0 so pip do not pick it by default)

**Comment by lmazuel** [comment]
Sorry for the late answer, 0.7.0 as been yanked from PyPI.
