### ISSUE TITLE
Question about certifi license compatibility

### ISSUE THREAD

**Issue by puthurr** [Azure/msrest-for-python#258]
Hi All,

Certifi package used in msrest highlights a [OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)](https://www.mozilla.org/en-US/MPL/2.0/) 
as seen in https://pypi.org/project/certifi/. 

msrest is MIT based. 

Isn't that creates a license incompatibility issue if I were to commercialize an application based on msrest ? 

Thanks in advance.

**Comment by lmazuel** [comment]
Hi @puthurr 
`msrest` is deprecated library, and we do not suggest people to use it anymore.
Please ping me on Teams if you want to discuss this further.
Thanks,
