### ISSUE TITLE
ansible azure storage DeserializationError

### ISSUE THREAD

**Issue by stacker2017** [Azure/msrest-for-python#75]
ansible version 2.4.2.0
 pip freeze
adal==0.4.7
ansible==2.4.2.0
applicationinsights==0.11.1
argcomplete==1.9.3
asn1crypto==0.24.0
azure-cli-core==2.0.23
azure-cli-nspkg==3.0.1
azure-common==1.1.8
azure-mgmt-batch==4.1.0
azure-mgmt-compute==2.1.0
azure-mgmt-containerservice==1.0.0
azure-mgmt-dns==1.2.0
azure-mgmt-keyvault==0.40.0
azure-mgmt-network==1.7.1
azure-mgmt-nspkg==2.0.0
azure-mgmt-resource==1.2.2
azure-mgmt-sql==0.7.1
azure-mgmt-storage==1.5.0
azure-mgmt-web==0.32.0
azure-nspkg==2.0.0
azure-storage==0.35.1
bcrypt==3.1.4
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
colorama==0.3.9
cryptography==2.1.4
enum34==1.1.6
humanfriendly==4.4.1
idna==2.6
ipaddress==1.0.19
isodate==0.6.0
Jinja2==2.10
jmespath==0.9.3
keyring==10.5.1
MarkupSafe==1.0
monotonic==1.4
msrest==0.4.22
msrestazure==0.4.19
oauthlib==2.0.6
packaging==16.8
paramiko==2.4.0
pyasn1==0.4.2
pycparser==2.18
pycrypto==2.6.1
Pygments==2.2.0
PyJWT==1.5.3
PyNaCl==1.2.1
pyOpenSSL==17.5.0
pyparsing==2.2.0
python-dateutil==2.6.1
PyYAML==3.12
requests==2.18.4
requests-oauthlib==0.8.0
SecretStorage==2.3.1
six==1.11.0
tabulate==0.7.7
urllib3==1.22

when I run the playbook:
- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create storage account
    azure_rm_storageaccount:
       resource_group: awx
       name: testaccount2018
       type: Standard_LRS
  - name: Create VM with defaults
    azure_rm_virtualmachine:
        resource_group: awx
        name: testvm10
        admin_username: ubuntu
        admin_password: Password123456
        image:
           offer: UbuntuServer
           publisher: Canonical
           sku: '16.04-LTS'
           version: latest

I get following deserialization error:
```python
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: msrest.exceptions.SerializationError: Unable to build a model: <SkuName.standard_lrs: 'Standard_LRS'> is not valid value for enum <enum 'SkuName'>, DeserializationError: <SkuName.standard_lrs: 'Standard_LRS'> is not valid value for enum <enum 'SkuName'>
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):
  File "/tmp/ansible_DUBaJU/ansible_module_azure_rm_storageaccount.py", line 462, in <module>
    main()
  File "/tmp/ansible_DUBaJU/ansible_module_azure_rm_storageaccount.py", line 459, in main
    AzureRMStorageAccount()
  File "/tmp/ansible_DUBaJU/ansible_module_azure_rm_storageaccount.py", line 204, in __init__
    supports_check_mode=True)
  File "/tmp/ansible_DUBaJU/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 285, in __init__
  File "/tmp/ansible_DUBaJU/ansible_module_azure_rm_storageaccount.py", line 240, in exec_module
    self.results['state'] = self.create_account()
  File "/tmp/ansible_DUBaJU/ansible_module_azure_rm_storageaccount.py", line 416, in create_account
    poller = self.storage_client.storage_accounts.create(self.resource_group, self.name, parameters)
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/storage/v2017_06_01/operations/storage_accounts_operations.py", line 159, in create
    body_content = self._serialize.body(parameters, 'StorageAccountCreateParameters')
  File "/usr/local/lib/python2.7/dist-packages/msrest/serialization.py", line 466, in body
    SerializationError, "Unable to build a model: "+str(err), err)
  File "/usr/local/lib/python2.7/dist-packages/msrest/exceptions.py", line 48, in raise_with_traceback
    raise error
msrest.exceptions.SerializationError: Unable to build a model: <SkuName.standard_lrs: 'Standard_LRS'> is not valid value for enum <enum 'SkuName'>, DeserializationError: <SkuName.standard_lrs: 'Standard_LRS'> is not valid value for enum <enum 'SkuName'>
", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}"
```

I know Standard_LRS is a valid storage type, just not sure why python code is complaing..

**Comment by lmazuel** [comment]
Short workaround: downgrade your azure-mgmt-storage to 1.4.0.

Long answer, that's an incorrect use of the SDK by Ansible, and `msrest` being too much nervous on enum checking. I'm working to make this more lenient today.
Thanks for the bug report

@tstringer

**Comment by stacker2017** [comment]
@lmazuel Thank you very much for the hint, the workaround worked

**Comment by lmazuel** [comment]
msrest 0.4.23 is released and more lenient, this should fix Ansible issue. Still does not change that there is also a fix to do in Ansible, but at least should be ok for now.

**Comment by Anshapar** [comment]
I am getting the same kind of error while accessing storage account of kind FileStorage:
msrest.exceptions.SerializationError: u'FileStorage' is not valid value for enum <enum 'Kind'
