### ISSUE TITLE
msrest debug logging includes request/response body in clear text

### ISSUE THREAD

**Issue by annatisch** [Azure/msrest-for-python#83]
This causes problems when the request and/or response container sensitive data that is then persisted to log files.

**Comment by lmazuel** [comment]
We can't do anything at the `msrest` level, unless someone wants to add a Swagger extension to tag critical info, But SDK owners can add logging filter to the msrest logger

```python
def myfilter(record):
   if contains_critical_stuff(record):
      change_record(record):
   return True # False means don't log it at all
logging.getLogger("msrest").addFilter(myfilter)
```

This can be put in any `__init__` file. This is the recommended approach discussed with @johanste
