### ISSUE TITLE
Error when pushing app to Azure

### ISSUE THREAD

**Issue by yannDroy** [Azure/msrest-for-python#96]
I created a chatbot with Python SDK. When I want to push it to Azure, following [this](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-python) tutorial, the installation or requirements is failing:
`Cloning https://github.com/Azure/msrest-for-python.git to d:\local\temp\pip-5vs3vmb1-build
remote:   Running setup.py (path:D:\local\Temp\pip-5vs3vmb1-build\setup.py) egg_info for package from git+https://github.com/Azure/msrest-for-python.git
remote:     error in msrest setup command: Invalid environment marker: python_version<'3.4'
remote:     Complete output from command python setup.py egg_info:
remote:     error in msrest setup command: Invalid environment marker: python_version<'3.4'`

**Comment by yannDroy** [comment]
Here is the full output:

`Downloading/unpacking git+https://github.com/Azure/msrest-for-python.git (from -r requirements.txt (line 6))
remote:   Cloning https://github.com/Azure/msrest-for-python.git to d:\local\temp\pip-5vs3vmb1-build
remote:   Running setup.py (path:D:\local\Temp\pip-5vs3vmb1-build\setup.py) egg_info for package from git+https://github.com/Azure/msrest-for-python.git
remote:     error in msrest setup command: Invalid environment marker: python_version<'3.4'
remote:     Complete output from command python setup.py egg_info:
remote:     error in msrest setup command: Invalid environment marker: python_version<'3.4'
remote:
remote: ----------------------------------------
remote: Cleaning up...
remote:   Exception:
remote: Traceback (most recent call last):
remote:   File "D:\home\site\wwwroot\env\lib\site-packages\pip\commands\install.py", line 278, in run
remote:     requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
remote:   File "D:\home\site\wwwroot\env\lib\site-packages\pip\req.py", line 1229, in prepare_files
remote:     req_to_install.run_egg_info()
remote:   File "D:\home\site\wwwroot\env\lib\site-packages\pip\req.py", line 325, in run_egg_info
remote:     command_desc='python setup.py egg_info')
remote:   File "D:\home\site\wwwroot\env\lib\site-packages\pip\util.py", line 697, in call_subprocess
remote:     % (command_desc, proc.returncode, cwd))
remote: pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in D:\local\Temp\pip-5vs3vmb1-build
remote:
remote: During handling of the above exception, another exception occurred:
remote:
remote: Traceback (most recent call last):
remote:   File "D:\python34\lib\shutil.py", line 370, in _rmtree_unsafe
remote:     os.unlink(fullname)
remote: PermissionError: [WinError 5] Access is denied: 'D:\\local\\Temp\\pip-7yxx5ulk-build\\.git\\objects\\pack\\pack-3f4f46194b391ff12392840a05d41806120d9ef3.idx'
remote:
remote: During handling of the above exception, another exception occurred:
remote:
remote: Traceback (most recent call last):
remote:   File "D:\home\site\wwwroot\env\lib\site-packages\pip\basecommand.py", line 122, in main
remote:     status = self.run(options, args)
remote:   File "D:\home\site\wwwroot\env\lib\site-packages\pip\commands\install.py", line 302, in run
remote:     requirement_set.cleanup_files(bundle=self.bundle)
remote:   File "D:\home\site\wwwroot\env\lib\site-packages\pip\req.py", line 1319, in cleanup_files
remote:     req.remove_temporary_source()
remote:   File "D:\home\site\wwwroot\env\lib\site-packages\pip\req.py", line 761, in remove_temporary_source
remote:     rmtree(self._temp_build_dir)
remote:   File "D:\home\site\wwwroot\env\lib\site-packages\pip\util.py", line 43, in rmtree
remote:     onerror=rmtree_errorhandler)
remote:   File "D:\python34\lib\shutil.py", line 477, in rmtree
remote:     return _rmtree_unsafe(path, onerror)
remote:   File "D:\python34\lib\shutil.py", line 367, in _rmtree_unsafe
remote:     _rmtree_unsafe(fullname, onerror)
remote:   File "D:\python34\lib\shutil.py", line 367, in _rmtree_unsafe
remote:     _rmtree_unsafe(fullname, onerror)
remote:   File "D:\python34\lib\shutil.py", line 367, in _rmtree_unsafe
remote:     _rmtree_unsafe(fullname, onerror)
remote:   File "D:\python34\lib\shutil.py", line 372, in _rmtree_unsafe
remote:     onerror(os.unlink, fullname, sys.exc_info())
remote:   File "D:\home\site\wwwroot\env\lib\site-packages\pip\util.py", line 53, in rmtree_errorhandler
remote:     (exctype is PermissionError and value.args[3] == 5) #python3.3
remote: IndexError: tuple index out of range
remote:
remote:   Storing debug log for failure in D:\home\pip\pip.log
remote: An error has occurred during web site deployment.
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.`

**Comment by lmazuel** [comment]
Hi @yannDroy 
The default Python on Webapp is considered deprecated, since it has not been updated for a long time. The "pip" installed is old, and it's why you can't install "msrest".

So the tutorial will work for basic dependencies, but will likely fail for something more subtle (like the SDK for Python, numpy, etc.)

Short term solutions (ordered)
- Use Linux preview and containers:
https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-custom-docker-image
https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-docker-python-postgresql-app
https://azure.microsoft.com/en-us/updates/new-python-solutions-for-web-app-for-containers/
- Use an extension of Python: 
https://docs.microsoft.com/en-us/visualstudio/python/managing-python-on-azure-app-service
https://github.com/Azure-Samples/app-service-msi-keyvault-python
- Update pip in a venv using Kudu
https://stackoverflow.com/questions/43970307/azure-functions-installing-python-modules-and-extensions-on-consumption-plan/43984890#43984890

**Comment by lmazuel** [comment]
I'm closing the issue since it's not related to "msrest". Feel free to email me `<githubalias>@microsoft.com` if you still get trouble.
